### ISSUE TITLE
License for the Repo

### ISSUE THREAD

**Issue by goneall** [CycloneDX/bom-examples#22]
I would like to use these examples in unit tests for some software I am developing.

Is there a license for the examples or any restrictions on its use?

I realize that some may argue some data can not be copyrighted.  However, it would be nice to make it clear in the README and a LICENSE file how the data can be used.

[CC-BY-4.0](https://spdx.org/licenses/CC-BY-4.0.html) is a common license for this type of data if you would like attribution and [CC0-1.0](https://spdx.org/licenses/CC0-1.0.html) is a common license if you don't care about the attribution.

**Comment by stevespringett** [comment]
Thanks Gary. We've licensed it under CC0-1.0.

Also note that in the specification repo, we have several hundred BOMs we use for testing each version of the specification. v1.4 schema test BOMs are here: https://github.com/CycloneDX/specification/tree/master/tools/src/test/resources/1.4 That repo and all its contents are Apache 2.0 licensed.

**Comment by goneall** [comment]
Thanks @stevespringett for the license info and the test resource pointer.
