### ISSUE TITLE
How to generate SaasBom

### ISSUE THREAD

**Issue by 71aoo** [CycloneDX/bom-examples#39]
I'm wondering that how to generate SaasBom, and I haven't found any details from the CycloneDX repository so far.  
Can you please provide some example?
Thank you.

**Comment by stevespringett** [comment]
Some commercial providers produce SaaSBOMs. Vendors such as Apiiro and SecureStack do this today I believe. I'm not aware of any open source tools that do this, but there may be some.

**Comment by 71aoo** [comment]
Thank you
